#!/usr/bin/env python2.7

import requests
import json


status = {}

status["last_init_date"] = "just this"
status["state"] = "rig.state"
status["last_clean_date"] = "rig.last_clean_date"
status["last_experiment"] = "rig.last_experiment"
status["version"] = {"version":"test"}
status["alarms"] = {"rig.alarms":"test"}

pdata = json.dumps(status)
print pdata
print

#status = requests.put('http://ion/rundb/api/v1/rig/PGM_test/status/', data=pdata, headers={'content-type':'application/json'}, auth=('ionadmin', 'ionadmin'))
#print status
#print status.content
#print

resp1 = requests.get('http://ion/rundb/api/v1/rig/?format=json', auth=('ionadmin', 'ionadmin'))

print "What is now there"
print json.dumps(json.loads(resp1.content),indent=4)

